/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PetRouteImport } from './routes/pet'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ConfessionsRouteImport } from './routes/confessions'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutAppRouteImport } from './routes/about-app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UFollowsRouteImport } from './routes/u..follows'
import { Route as UUserIdRouteImport } from './routes/u.$userId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PetRoute = PetRouteImport.update({
  id: '/pet',
  path: '/pet',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfessionsRoute = ConfessionsRouteImport.update({
  id: '/confessions',
  path: '/confessions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAppRoute = AboutAppRouteImport.update({
  id: '/about-app',
  path: '/about-app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UFollowsRoute = UFollowsRouteImport.update({
  id: '/u/follows',
  path: '/u/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-app': typeof AboutAppRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/community': typeof CommunityRoute
  '/confessions': typeof ConfessionsRoute
  '/learn': typeof LearnRoute
  '/notifications': typeof NotificationsRoute
  '/pet': typeof PetRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/u/$userId': typeof UUserIdRoute
  '/u/follows': typeof UFollowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-app': typeof AboutAppRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/community': typeof CommunityRoute
  '/confessions': typeof ConfessionsRoute
  '/learn': typeof LearnRoute
  '/notifications': typeof NotificationsRoute
  '/pet': typeof PetRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/u/$userId': typeof UUserIdRoute
  '/u/follows': typeof UFollowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-app': typeof AboutAppRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/community': typeof CommunityRoute
  '/confessions': typeof ConfessionsRoute
  '/learn': typeof LearnRoute
  '/notifications': typeof NotificationsRoute
  '/pet': typeof PetRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/u/$userId': typeof UUserIdRoute
  '/u/follows': typeof UFollowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-app'
    | '/achievements'
    | '/auth'
    | '/checkin'
    | '/community'
    | '/confessions'
    | '/learn'
    | '/notifications'
    | '/pet'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/stats'
    | '/terms'
    | '/u/$userId'
    | '/u/follows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-app'
    | '/achievements'
    | '/auth'
    | '/checkin'
    | '/community'
    | '/confessions'
    | '/learn'
    | '/notifications'
    | '/pet'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/stats'
    | '/terms'
    | '/u/$userId'
    | '/u/follows'
  id:
    | '__root__'
    | '/'
    | '/about-app'
    | '/achievements'
    | '/auth'
    | '/checkin'
    | '/community'
    | '/confessions'
    | '/learn'
    | '/notifications'
    | '/pet'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/stats'
    | '/terms'
    | '/u/$userId'
    | '/u/follows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutAppRoute: typeof AboutAppRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  CheckinRoute: typeof CheckinRoute
  CommunityRoute: typeof CommunityRoute
  ConfessionsRoute: typeof ConfessionsRoute
  LearnRoute: typeof LearnRoute
  NotificationsRoute: typeof NotificationsRoute
  PetRoute: typeof PetRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  UUserIdRoute: typeof UUserIdRoute
  UFollowsRoute: typeof UFollowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet': {
      id: '/pet'
      path: '/pet'
      fullPath: '/pet'
      preLoaderRoute: typeof PetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confessions': {
      id: '/confessions'
      path: '/confessions'
      fullPath: '/confessions'
      preLoaderRoute: typeof ConfessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-app': {
      id: '/about-app'
      path: '/about-app'
      fullPath: '/about-app'
      preLoaderRoute: typeof AboutAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/follows': {
      id: '/u/follows'
      path: '/u/follows'
      fullPath: '/u/follows'
      preLoaderRoute: typeof UFollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutAppRoute: AboutAppRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  CheckinRoute: CheckinRoute,
  CommunityRoute: CommunityRoute,
  ConfessionsRoute: ConfessionsRoute,
  LearnRoute: LearnRoute,
  NotificationsRoute: NotificationsRoute,
  PetRoute: PetRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  UUserIdRoute: UUserIdRoute,
  UFollowsRoute: UFollowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
